spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "1.0"

loans:
  message: "Welcome to StudyBank PROD loans"
  contactDetails:
    name: "Sit Amet - Product Owner"
    email: "sit.amet@lipsum.com"
  onCallSupport:
    - (555) 333-1234
    - (555) 333-1345