spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "2.0"

cards:
  message: "Welcome to StudyBank QA cards"
  contactDetails:
    name: "Dolor Sit - QA Lead"
    email: "dolor.sit@lipsum.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 555-1345