services:
  accountsdb:
    container_name: accounts-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: accounts-db
    extends:
      file: common-config.yml
      service: microservice-database-config

  loansdb:
    container_name: loans-db
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: loans-db
    extends:
      file: common-config.yml
      service: microservice-database-config

  cardsdb:
    container_name: cards-db
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: cards-db
    extends:
      file: common-config.yml
      service: microservice-database-config

  configserver:
    image: "dirso/configserver-ms:s7"
    container_name: configserver-ms
    ports:
      - "8071:8071"
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: network-deploy-service

  accounts:
    image: "dirso/accounts-ms:s7"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    depends_on:
      accountsdb:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "accounts"
      SPRING_DATASOURCE_URL: "jdbc:mysql://accountsdb:3306/accounts-db"
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  loans:
    image: "dirso/loans-ms:s7"
    container_name: loans-ms
    ports:
      - "8090:8090"
    depends_on:
      loansdb:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "loans"
      SPRING_DATASOURCE_URL: "jdbc:mysql://loansdb:3306/loans-db"
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  cards:
    image: "dirso/cards-ms:s7"
    container_name: cards-ms
    ports:
      - "9000:9000"
    depends_on:
      cardsdb:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "cards"
      SPRING_DATASOURCE_URL: "jdbc:mysql://cardsdb:3306/cards-db"
    extends:
      file: common-config.yml
      service: microservice-configserver-config

networks:
  studybank:
    driver: "bridge"