build:
  version: "1.0"

accounts:
  message: "Welcome to StudyBank PROD accounts"
  contactDetails:
    name: "Sit Amet - Product Owner"
    email: "sit.amet@lipsum.com"
  onCallSupport:
    - (555) 333-1234
    - (555) 333-1345