services:
  accounts:
    image: "dirso/accounts-microservice:s4"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - "studybank"
  loans:
    image: "dirso/loans-microservice:s4"
    container_name: loans-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - "studybank"
  cards:
    image: "dirso/cards-microservice:s4"
    container_name: cards-ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - "studybank"
networks:
  studybank:
    driver: "bridge"